const products = [
  {
    name: "Premium Wireless Headphones",
    image: "/uploads/headphones.png",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life",
    brand: "SoundMax",
    price: 199.99,
    category: "507f1f77bcf86cd799439011",
    quantity: 50,
    countInStock: 50,
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "4K Wireless Camera",
    image: "/uploads/camera.png",
    description: "Crystal clear 4K video recording with WiFi connectivity",
    brand: "PixelPro",
    price: 299.99,
    category: "507f1f77bcf86cd799439012",
    quantity: 30,
    countInStock: 30,
    rating: 4.8,
    numReviews: 25,
  },
  {
    name: "Smart Watch Ultra",
    image: "/uploads/smartwatch.png",
    description: "Feature-rich smartwatch with health monitoring and 7-day battery",
    brand: "TechWear",
    price: 249.99,
    category: "507f1f77bcf86cd799439013",
    quantity: 45,
    countInStock: 45,
    rating: 4.3,
    numReviews: 15,
  },
  {
    name: "USB-C Fast Charger",
    image: "/uploads/charger.png",
    description: "65W Ultra-fast USB-C charger compatible with all devices",
    brand: "PowerTech",
    price: 39.99,
    category: "507f1f77bcf86cd799439014",
    quantity: 100,
    countInStock: 100,
    rating: 4.6,
    numReviews: 50,
  },
  {
    name: "Mechanical Keyboard RGB",
    image: "/uploads/keyboard.png",
    description: "Professional mechanical keyboard with RGB backlighting",
    brand: "KeyMaster",
    price: 129.99,
    category: "507f1f77bcf86cd799439015",
    quantity: 40,
    countInStock: 40,
    rating: 4.7,
    numReviews: 30,
  },
  {
    name: "Portable SSD 1TB",
    image: "/uploads/ssd.png",
    description: "Ultra-fast portable solid state drive with 1TB capacity",
    brand: "StorageX",
    price: 149.99,
    category: "507f1f77bcf86cd799439016",
    quantity: 35,
    countInStock: 35,
    rating: 4.9,
    numReviews: 40,
  },
];

export default products;
